export const DATA_PRODUCT = [
  {
    id: 1,
    type: 'message',
    category: 'generic',
    sub_category: 'insertion',
    question:
      'Hi, we are at the Lulu Hypermarket Karama for surveying the following 3 SKUs of Nivea Skin Firming Body Lotion\n',
    response_required: 'No',
    response_method: 'NA',
    response_type: 'NA',
    response_recording: 'NA',
    picture_required: 'NA',
    validation_required: 'NA',
  },
  {
    id: 2,
    type: 'message',
    category: 'generic',
    sub_category: 'insertion',
    question:
      'Please visit the Skincare section in the store to start the survey\n\n\n',
    hint: 'OK, I am at the Skincare section to start the survey',
    response_required: 'No',
    response_method: 'NA',
    response_type: 'NA',
    response_recording: 'NA',
    picture_required: 'NA',
    validation_required: 'NA',
  },
  {
    id: 3,
    type: 'survey',
    category: 'category',
    sub_category: 'category',
    question:
      'What is the name of the section (as displayed in the store) where the below products are placed\n',
    images: ['p1.png', 'p2.png', 'p3.png', 'p4.png'],
    inputText: '',
    imageFile: '',
    imageUrl: '',
    response_required: 'Yes',
    response_method: 'Free Text',
    response_type: 'number',
    response_recording: 'Text',
    picture_required: 'Yes',
    validation_required: 'No',
  },
  {
    id: 4,
    type: 'survey',
    category: 'category',
    sub_category: 'category size',
    question: "Let's measure the size of the SKINCARE category in this store\n",
    hint: 'Measuring tape should be used for the measurements (Click to know more)',
    meters: 0,
    centimeters: 0,
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'No',
    validation_required: 'Yes',
  },
  {
    id: 5,
    type: 'survey',
    category: 'category',
    sub_category: 'category size',
    question:
      "Great, Now let's measure the shelve space allocated to the products shown below\n\n\n",
    images: ['p1.png', 'p2.png', 'p3.png', 'p4.png'],
    hint: 'Measuring tape should be used for the measurements (Click to know more)',
    meters: 0,
    centimeters: 0,
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'No',
    validation_required: 'Yes',
  },
  {
    id: 6,
    type: 'survey',
    category: 'primary availability',
    sub_category: 'product availability',
    question:
      'Select the products that are displayed on the shelf in front of you\n\n',
    options: [
      {
        image: 'p1.png',
        checked: null,
      },
      {
        image: 'p2.png',
        checked: null,
      },
      {
        image: 'p3.png',
        checked: null,
      },
      {
        image: 'p4.png',
        checked: null,
      },
    ],
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'count',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 7,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'product facings',
    question:
      'Count the facings of the following products as displayed on the shelves\n',
    hint: 'Facings are the number of units of the SKUs displayed on the front row\nDo not count units kept in the back rows',
    images: ['p1.png', 'p2.png', 'p3.png', 'p4.png'],
    count: 0,
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 8,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'sku facings',
    question:
      'How many facings of Skin Firming Nourishing Hydration 400 ML Body Lotion are kept on the shelf\n',
    hint: 'Facings are the number of units of the SKUs displayed on the front row\nDo not count units kept in the back rows',
    images: ['p1.png', 'p2.png', 'p3.png', 'p4.png'],
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 9,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'sku placement',
    question:
      'How many facings of Skin Firming Nourishing Hydration 400 ML Body Lotion are kept on the shelf in front of you that you can reach out without bending with straight hand to pick\n',
    hint: 'Facings are the number of units of the SKUs displayed on the front row\nDo not count units kept in the back rows',
    images: ['p1.png', 'p2.png', 'p3.png', 'p4.png'],
    count: 0,
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 10,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'sku placement',
    question:
      'How many facings of Skin Firming Nourishing Hydration 400 ML Body Lotion are kept on other shelves for which you have to either bend or raise your hand to pick\n',
    count: 0,
    images: ['p1.png', 'p2.png', 'p3.png', 'p4.png'],
    hint: 'Facings are the number of units of the SKUs displayed on the front row\nDo not count units kept in the back rows',
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 11,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'sku facings',
    question:
      'How many facings of Skin Firming Sheer Hydration 400 ML Body Lotion are kept on the shelf\n',
    image: 'p1.png',
    hint: 'Facings are the number of units of the SKUs displayed on the front row\nDo not count units kept in the back rows',
    count: 0,
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 12,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'sku placement',
    question:
      'How many facings of Skin Firming Sheer Hydration 400 ML Body Lotion  are kept on the shelf in front of you that you can reach out without bending with straight hand to pick\n',
    image: 'p2.png',
    count: 0,
    hint: 'Facings are the number of units of the SKUs displayed on the front row\nDo not count units kept in the back rows',
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 13,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'sku placement',
    question:
      'How many facings of Skin Firming Sheer Hydration 400 ML Body Lotion  are kept on the shelf in front of you that you can reach out without bending with straight hand to pick\n',
    hint: 'Facings are the number of units of the SKUs displayed on the front row\nDo not count units kept in the back rows',
    image: 'p2.png',
    count: 0,
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 14,
    question:
      'How many facings of Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion are kept on the shelf\n',
    hint: 'Facings are the number of units of the SKUs displayed on the front row\nDo not count units kept in the back rows',
    image: 'p2.png',
    count: 0,
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 15,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'sku facings',
    question:
      'How many facings of Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion  are kept on the shelf in front of you that you can reach out without bending with straight hand to pick\n',
    hint: 'Facings are the number of units of the SKUs displayed on the front row\nDo not count units kept in the back rows',
    image: 'p2.png',
    count: 0,
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 16,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'sku placement',
    question:
      'How many facings of Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion  are kept on the shelf in front of you that you can reach out without bending with straight hand to pick\n',
    hint: 'Facings are the number of units of the SKUs displayed on the front row\nDo not count units kept in the back rows',
    image: 'p2.png',
    count: 0,
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 17,
    type: 'message',
    category: 'generic',
    sub_category: 'insertion',
    question:
      "Great going, let's now get some data collected for the primary branding done in this section.\nFollowing are some of the primary branding material, we shall survey\n\n",
    imageg: ['p1.png', 'p2.png', 'p3.png', 'p4.png'],
    response_required: 'No',
    response_method: 'NA',
    response_type: 'NA',
    response_recording: 'NA',
    picture_required: 'NA',
    validation_required: 'NA',
  },
  {
    id: 18,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'primary branding',
    question: 'Do you see a Wobbler displayed on the shelves in front of you\n',
    image: 'p1.png',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 19,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'primary branding',
    question:
      'Do you see a Shelf Separator displayed on the shelves in front of you\n',
    image: 'p3.png',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 20,
    type: 'survey',
    category: 'primary visibility',
    sub_category: 'primary branding',
    question:
      'Do you see a Shelf Strip displayed on the shelves in front of you\n',
    image: 'p4.png',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 21,
    type: 'message',
    category: 'generic',
    sub_category: 'insertion',
    question:
      "Now that we are done with the survey of the primary section\nLet's move to survey the secondary placements of our products in this store",
    response_required: 'No',
    response_method: 'NA',
    response_type: 'NA',
    response_recording: 'NA',
    picture_required: 'NA',
    validation_required: 'NA',
  },
  {
    id: 22,
    type: 'message',
    category: 'generic',
    sub_category: 'insertion',
    question:
      'We shall be surveying the following secondary placements in the store\n',
    images: ['p6.png', 'p7.png'],
    note: 'Let’s start',
    response_required: 'No',
    response_method: 'NA',
    response_type: 'NA',
    response_recording: 'NA',
    picture_required: 'NA',
    validation_required: 'NA',
  },
  {
    id: 23,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'How many Gondola Ends as shown in the picture below do you see at the store\n',
    image: 'p3.png',
    hint: 'Please walk around the store before answering this question\n<+/->',
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 24,
    type: 'message',
    category: 'generic',
    sub_category: 'insertion',
    question:
      "Now that you have located the Gondola Ends, let's start answering some questions about them ",
    response_required: 'No',
    response_method: 'NA',
    response_type: 'NA',
    response_recording: 'NA',
    picture_required: 'NA',
    validation_required: 'NA',
  },
  {
    id: 25,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Please provide the name of section where this Gondola End is kept in the store\n',
    image: 'p4.png',
    inputValue: '',
    response_required: 'Yes',
    response_method: 'Free Text',
    response_type: 'Text',
    response_recording: 'Text',
    picture_required: 'Yes',
    validation_required: 'No',
  },
  {
    id: 26,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the branding on the Gondola Header same as the one displayed in the below picture\n',
    image: 'p1.png',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 27,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the branding on the Gondola Bottom section same as the one displayed in the below picture\n',
    image: 'p1.png',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 28,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the branding on the Gondola Left side section same as the one displayed in the below picture\n',
    image: 'p3.png',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 29,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the branding on the Gondola Right side section same as the one displayed in the below picture\n',
    image: 'p2.png',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 30,
    type: 'survey',
    category: 'secondary availability',
    sub_category: 'Gondola End',
    question: 'Select the SKUs that are displayed on the Gondola Shelves\n\n',
    options: [
      {
        image: 'p1.png',
        checked: null,
      },
      {
        image: 'p2.png',
        checked: null,
      },
      {
        image: 'p3.png',
        checked: null,
      },
      {
        image: 'p4.png',
        checked: null,
      },
    ],
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'count',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 31,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Do you see any SKUs other than the following SKUs placed on the Gondola\n<SKU Images>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 32,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the 1st shelf of the Gondola looking same as displayed in the picture below\n<Gondola Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 33,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the 2nd shelf of the Gondola looking same as displayed in the picture below\n<Gondola Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 34,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the 3rd shelf of the Gondola looking same as displayed in the picture below\n<Gondola Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 35,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the 4th shelf of the Gondola looking same as displayed in the picture below\n<Gondola Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 36,
    type: 'message',
    category: 'generic',
    sub_category: 'insertion',
    question: "OK, let's move to the Next Gondola End",
    response_required: 'No',
    response_method: 'NA',
    response_type: 'NA',
    response_recording: 'NA',
    picture_required: 'NA',
    validation_required: 'NA',
  },
  {
    id: 37,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Please provide the name of section where this Gondola End is kept in the store\n<Gondola Picture>\n<Free Text>\n\n',
    response_required: 'Yes',
    response_method: 'Free Text',
    response_type: 'Text',
    response_recording: 'Text',
    picture_required: 'Yes',
    validation_required: 'No',
  },
  {
    id: 38,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the branding on the Gondola Header same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 39,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the branding on the Gondola Bottom section same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 40,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the branding on the Gondola Left side section same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 41,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the branding on the Gondola Right side section same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 42,
    type: 'survey',
    category: 'secondary availability',
    sub_category: 'Gondola End',
    question:
      'Select the SKUs that are displayed on the Gondola Shelves\n\n<SKU Images shown with selection option>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'count',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 43,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Do you see any SKUs other than the following SKUs placed on the Gondola\n<SKU Images>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 44,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the 1st shelf of the Gondola looking same as displayed in the picture below\n<Gondola Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 45,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the 2nd shelf of the Gondola looking same as displayed in the picture below\n<Gondola Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 46,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the 3rd shelf of the Gondola looking same as displayed in the picture below\n<Gondola Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 47,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'Is the 4th shelf of the Gondola looking same as displayed in the picture below\n<Gondola Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 48,
    type: 'message',
    category: 'generic',
    sub_category: 'insertion',
    question:
      "Let's now move to survey the Free Standing Units (FSUs) in the store\n\n<FSU Image>\n\n<OK>",
    response_required: 'No',
    response_method: 'NA',
    response_type: 'NA',
    response_recording: 'NA',
    picture_required: 'NA',
    validation_required: 'NA',
  },
  {
    id: 49,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'Gondola End',
    question:
      'How many FSUs as shown in the picture below do you see at the store\n<Gondola Picture>\nPlease walk around the store before answering this question\n<+/->\n',
    response_required: 'Yes',
    response_method: '+/-',
    response_type: 'number',
    response_recording: 'integer',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 50,
    type: 'message',
    category: 'generic',
    sub_category: 'insertion',
    question:
      "Now that you have located the FSUs, let's start answering some questions about them ",
    response_required: 'No',
    response_method: 'NA',
    response_type: 'NA',
    response_recording: 'NA',
    picture_required: 'NA',
    validation_required: 'NA',
  },
  {
    id: 51,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Please provide the name of section where this FSU is kept in the store\n<FSU Picture>\n<Free Text>\n\n',
    response_required: 'Yes',
    response_method: 'Free Text',
    response_type: 'Text',
    response_recording: 'Text',
    picture_required: 'Yes',
    validation_required: 'No',
  },
  {
    id: 52,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the branding on the FSU Header same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 53,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the branding on the FSU Bottom section same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 54,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the branding on the FSU Left side section same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 55,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the branding on the FSU Right side section same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 56,
    type: 'survey',
    category: 'secondary availability',
    sub_category: 'FSU',
    question:
      'Select the SKUs that are displayed on the FSU Shelves\n\n<SKU Images shown with selection option>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'count',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 57,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Do you see any SKUs other than the following SKUs placed on the FSU\n<SKU Images>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 58,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the 1st shelf of the FSU looking same as displayed in the picture below\n<FSU Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 59,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the 2nd shelf of the FSU looking same as displayed in the picture below\n<FSU Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 60,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the 3rd shelf of the FSU looking same as displayed in the picture below\n<FSU Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 61,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the 4th shelf of the FSU looking same as displayed in the picture below\n<FSU Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 62,
    type: 'message',
    category: 'generic',
    sub_category: 'insertion',
    question: "OK, let's move to the Next FSU",
    response_required: 'No',
    response_method: 'NA',
    response_type: 'NA',
    response_recording: 'NA',
    picture_required: 'NA',
    validation_required: 'NA',
  },
  {
    id: 63,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Please provide the name of section where this FSU is kept in the store\n<FSU Picture>\n<Free Text>\n\n',
    response_required: 'Yes',
    response_method: 'Free Text',
    response_type: 'Text',
    response_recording: 'Text',
    picture_required: 'Yes',
    validation_required: 'No',
  },
  {
    id: 64,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the branding on the FSU Header same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 65,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the branding on the FSU Bottom section same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 66,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the branding on the FSU Left side section same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 67,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the branding on the FSU Right side section same as the one displayed in the below picture\n<Sample Picture>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 68,
    type: 'survey',
    category: 'secondary availability',
    sub_category: 'FSU',
    question:
      'Select the SKUs that are displayed on the FSU Shelves\n\n<SKU Images shown with selection option>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'count',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 69,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Do you see any SKUs other than the following SKUs placed on the FSU\n<SKU Images>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 70,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the 1st shelf of the FSU looking same as displayed in the picture below\n<FSU Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 71,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the 2nd shelf of the FSU looking same as displayed in the picture below\n<FSU Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 72,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the 3rd shelf of the FSU looking same as displayed in the picture below\n<FSU Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
  {
    id: 73,
    type: 'survey',
    category: 'secondary visibility',
    sub_category: 'FSU',
    question:
      'Is the 4th shelf of the FSU looking same as displayed in the picture below\n<FSU Image>\n<Yes/No>',
    response_required: 'Yes',
    response_method: 'selection',
    response_type: 'yes/no',
    response_recording: 'varchar',
    picture_required: 'Yes',
    validation_required: 'Yes',
  },
];
