export const PRODUCT_QUESTIONS=[
    {
        id: 1,
        quetion:"What is the name of the section (as displayed in the store) where the below products are placed?",
        products:[
            "pr3.jpg",
            "pr1.jpg",
            "pr2.jpg"
        ],
        answer: undefined,
        time: 0,
        type:"meter-image",
        file: undefined,
        image: undefined
    },
    {
        id: 2,
        quetion:"Let's measure the size of the <strong>SKINCARE</strong> category in this store.",
        answer: undefined,
        time: 0,
        type:"meter",
        meters: 0,
        centimeter: 0
    },
    {
        id: 3,
        quetion:"Great, Now let's measure the shelf space allocated to the products shown below",
        answer: undefined,
        time: 0,
        type:"meter-image-second",
        meters: 0,
        centimeter: 0,
    },
    {
        id: 4,
        quetion:"Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the shelf?",
        answer: undefined,
        productImage:"pr3.jpg",
        time: 0,
        type:"single-question-yes-no",
    },
    {
        id: 5,
        quetion:"How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the shelf?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr3.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 6,
        quetion:"How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the shelf in front of you that you can reach out without bending with straight hand to pick?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr3.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 7,
        quetion:"How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on other shelves for which you have to either bend or raise your hand to pick?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr3.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 8,
        quetion:"Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the shelf?",
        answer: undefined,
        productImage:"pr1.jpg",
        time: 0,
        type:"single-question-yes-no",
    },
    {
        id: 9,
        quetion:"How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the shelf?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr1.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 10,
        quetion:"How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the shelf in front of you that you can reach out without bending with straight hand to pick?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr1.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 11,
        quetion:"How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on other shelves for which you have to either bend or raise your hand to pick?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr1.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 12,
        quetion:"Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the shelf?",
        answer: undefined,
        productImage:"pr2.jpg",
        time: 0,
        type:"single-question-yes-no",
    },
    {
        id: 13,
        quetion:"How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the shelf?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr2.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 14,
        quetion:"How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the shelf in front of you that you can reach out without bending with straight hand to pick?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr2.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 15,
        quetion:"How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on other shelves for which you have to either bend or raise your hand to pick?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr2.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 16,
        quetion:"Do you see a <strong>Wobbler</strong> displayed on the shelves in front of you?",
        answer: undefined,
        time: 0,
        type:"single-question-yes-no",
        productImage:'p7.png',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 17,
        quetion:"Do you see a <strong>Shelf Separator</strong> displayed on the shelves in front of you?",
        answer: undefined,
        time: 0,
        type:"single-question-yes-no",
        productImage:'p6.png',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 18,
        quetion:"Do you see a <strong>Shelf Strip</strong> displayed on the shelves in front of you?",
        answer: undefined,
        time: 0,
        type:"single-question-yes-no",
        productImage:'p8.png',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 19,
        quetion:"Great JOB !!!<br/>Let's now proceed with the survey of the <strong>Gondola End</strong> placed in the store as shown in the image below.",
        answer: undefined,
        hint:"Please walk around various sections and proceed once you have seen a Gondola End",
        time: 0,
        type:"question-info",
    },
    {
        id: 20,
        quetion:"Please provide the name of section where this <strong>Gondola End</strong> is kept in the store.",
        products:[
            "gondola.jpg"
        ],
        answer: undefined,
        time: 0,
        type:"meter-image",
        file: undefined,
        image: undefined
    },
    {
        id: 21,
        quetion:"Is the branding on the <strong>Gondola</strong> same as the one displayed in the below picture?",
        answer: undefined,
        time: 0,
        type:"single-question-yes-no",
        productImage:'gondola.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 22,
        quetion:"Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage:"pr3.jpg",
        time: 0,
        type:"single-question-yes-no",
    },
    {
        id: 23,
        quetion:"How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr3.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 24,
        quetion:"Is the display of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr3.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 25,
        quetion:"Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage:"pr1.jpg",
        time: 0,
        type:"single-question-yes-no",
    },
    {
        id: 26,
        quetion:"How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr1.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 27,
        quetion:"Is the display of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr1.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 28,
        quetion:"Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage:"pr2.jpg",
        time: 0,
        type:"single-question-yes-no",
    },
    {
        id: 29,
        quetion:"How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr2.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 30,
        quetion:"Is the display of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr2.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 31,
        quetion:"Great going !!!<br/>Let's now move to the next <strong>Gondola End</strong> kept in the store.",
        answer: undefined,
        hint:"\n",
        time: 0,
        type:"question-info",
    },
    {
        id: 32,
        quetion:"Please provide the name of section where this <strong>Gondola End</strong> is kept in the store.",
        products:[
            "gondola.jpg"
        ],
        answer: undefined,
        time: 0,
        type:"meter-image",
        file: undefined,
        image: undefined
    },
    {
        id: 33,
        quetion:"Is the branding on the <strong>Gondola</strong> same as the one displayed in the below picture?",
        answer: undefined,
        time: 0,
        type:"single-question-yes-no",
        productImage:'gondola.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 34,
        quetion:"Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage:"pr3.jpg",
        time: 0,
        type:"single-question-yes-no",
    },
    {
        id: 35,
        quetion:"How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr3.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 36,
        quetion:"Is the display of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr3.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 37,
        quetion:"Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage:"pr1.jpg",
        time: 0,
        type:"single-question-yes-no",
    },
    {
        id: 38,
        quetion:"How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr1.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 39,
        quetion:"Is the display of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr1.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 40,
        quetion:"Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage:"pr2.jpg",
        time: 0,
        type:"single-question-yes-no",
    },
    {
        id: 41,
        quetion:"How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr2.jpg',
        counts: 0,
        file:"",
        image:""
    },
    {
        id: 42,
        quetion:"Is the display of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type:"meter-count",
        productImage:'pr2.jpg',
        counts: 0,
        file:"",
        image:""
    },
]