export const PRODUCT_QUESTIONS = [
    {
        id: 1,
        quetion: "What is the name of the section (as displayed in the store) where the below products are placed?",
        products: [
            "pr3.jpg",
            "pr1.jpg",
            "pr2.jpg"
        ],
        answer: undefined,
        time: 0,
        type: "meter-image",
        file: undefined,
        image: undefined
    },
    {
        id: 2,
        quetion: "Let's measure the size of the <strong>SKINCARE</strong> category in this store.",
        answer: undefined,
        time: 0,
        type: "meter",
        meters: 0,
        centimeter: 0
    },
    {
        id: 3,
        quetion: "Great, Now let's measure the shelf space allocated to the products shown below",
        answer: undefined,
        time: 0,
        type: "meter-image-second",
        meters: 0,
        centimeter: 0,
    },
    {
        id: 4,
        quetion: "Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the shelf?",
        answer: undefined,
        productImage: "pr3.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 5,
        quetion: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the shelf?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr3.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 6,
        quetion: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the shelf in front of you that you can reach out without bending with straight hand to pick?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr3.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 7,
        quetion: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on other shelves for which you have to either bend or raise your hand to pick?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr3.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 8,
        quetion: "Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the shelf?",
        answer: undefined,
        productImage: "pr1.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 9,
        quetion: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the shelf?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr1.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 10,
        quetion: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the shelf in front of you that you can reach out without bending with straight hand to pick?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr1.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 11,
        quetion: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on other shelves for which you have to either bend or raise your hand to pick?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr1.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 12,
        quetion: "Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the shelf?",
        answer: undefined,
        productImage: "pr2.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 13,
        quetion: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the shelf?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr2.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 14,
        quetion: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the shelf in front of you that you can reach out without bending with straight hand to pick?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr2.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 15,
        quetion: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on other shelves for which you have to either bend or raise your hand to pick?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr2.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 16,
        quetion: "Do you see a <strong>Wobbler</strong> displayed on the shelves in front of you?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'p7.png',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 17,
        quetion: "Do you see a <strong>Shelf Separator</strong> displayed on the shelves in front of you?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'p6.png',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 18,
        quetion: "Do you see a <strong>Shelf Strip</strong> displayed on the shelves in front of you?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'p8.png',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 19,
        quetion: "Great JOB !!!<br/>Let's now proceed with the next survey section.",
        answer: undefined,
        hint: "\n",
        time: 0,
        type: "question-info",
    },
    {
        id: 20,
        quetion: "Pls walk around various sections and proceed once you have seen any of sections displayed in the below images.",
        answer: undefined,
        time: 0,
        type: "gondola-fsu-selection",
        products: [
            {
                selection:"gondola",
                image:"gondola.jpg"
            },
            {
                selection:"fsu",
                image:"fsu.jpg"
            }
        ],
    },
]

export const GONDOLA_QUESTIONS=[
    {
        id: 21,
        quetion: "OK,<br/>Let's start with the survey of <strong>Gondola End</strong>.",
        answer: undefined,
        hint: "\n",
        time: 0,
        type: "question-info",
    },
    {
        id: 22,
        quetion: "Please provide the name of section where this <strong>Gondola End</strong> is kept in the store.",
        products: [
            "gondola.jpg"
        ],
        answer: undefined,
        time: 0,
        type: "meter-image",
        file: undefined,
        image: undefined
    },
    {
        id: 23,
        quetion: "Is the branding on the <strong>Gondola</strong> same as the one displayed in the below picture?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'gondola.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 24,
        quetion: "Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage: "pr3.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 25,
        quetion: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr3.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 26,
        quetion: "Is the display of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr3.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 27,
        quetion: "Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage: "pr1.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 28,
        quetion: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr1.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 29,
        quetion: "Is the display of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr1.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 30,
        quetion: "Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage: "pr2.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 31,
        quetion: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr2.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 32,
        quetion: "Is the display of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr2.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 33,
        quetion: "Great going !!!<br/>Let's now move to the next <strong>Gondola End</strong> kept in the store.",
        answer: undefined,
        hint: "\n",
        time: 0,
        type: "question-info",
    },
    {
        id: 34,
        quetion: "Please provide the name of section where this <strong>Gondola End</strong> is kept in the store.",
        products: [
            "gondola.jpg"
        ],
        answer: undefined,
        time: 0,
        type: "meter-image",
        file: undefined,
        image: undefined
    },
    {
        id: 35,
        quetion: "Is the branding on the <strong>Gondola</strong> same as the one displayed in the below picture?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'gondola.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 36,
        quetion: "Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage: "pr3.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 37,
        quetion: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr3.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 38,
        quetion: "Is the display of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr3.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 39,
        quetion: "Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage: "pr1.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 40,
        quetion: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr1.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 41,
        quetion: "Is the display of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr1.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 42,
        quetion: "Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the Gondola End?",
        answer: undefined,
        productImage: "pr2.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 43,
        quetion: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the Gondola shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr2.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 44,
        quetion: "Is the display of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> on the Gondola Shelves same as displayed in the Gondola Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr2.jpg',
        counts: 0,
        file: "",
        image: ""
    }
];

export const FSU_QUESTIONS=[
    {
        id: 45,
        quetion: "Great JOB !!!<br/>Let's now proceed with the survey of the <strong>FSUs</strong> or <strong>Free Standing Units</strong> placed in the store as shown in the image below.",
        answer: undefined,
        hint: "Pls walk around various sections and proceed once you have seen a FSU",
        time: 0,
        type: "question-info",
    },
    {
        id: 46,
        quetion: "How many <strong>FSUs</strong> as displayed in the Image below did you see in the store?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'fsu.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 47,
        quetion: "OK,<br/>Let's start with the survey of the first <strong>FSUs</strong>",
        answer: undefined,
        hint: "\n",
        time: 0,
        type: "question-info",
    },
    {
        id: 48,
        quetion: "Please provide the name of section where this <strong>FSU</strong> is kept in the store.",
        products: [
            "fsu.jpg"
        ],
        answer: undefined,
        time: 0,
        type: "meter-image",
        file: undefined,
        image: undefined
    },
    {
        id: 49,
        quetion: "Is the branding on the <strong>FSU</strong> same as the one displayed in the below picture?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'fsu.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 50,
        quetion: "Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the FSU?",
        answer: undefined,
        productImage: "pr3.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 51,
        quetion: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr3.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 52,
        quetion: "Is the display of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr3.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 53,
        quetion: "Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the FSU?",
        answer: undefined,
        productImage: "pr1.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 54,
        quetion: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr1.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 55,
        quetion: "Is the display of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr1.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 56,
        quetion: "Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the FSU?",
        answer: undefined,
        productImage: "pr2.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 57,
        quetion: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr2.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 58,
        quetion: "Is the display of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr2.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 59,
        quetion: "Great going !!!<br/>Let's now move to the next <strong>FSU</strong> kept in the store.",
        answer: undefined,
        hint: "\n",
        time: 0,
        type: "question-info",
    },
    {
        id: 60,
        quetion: "Please provide the name of section where this <strong>FSU</strong> is kept in the store.",
        products: [
            "fsu.jpg"
        ],
        answer: undefined,
        time: 0,
        type: "meter-image",
        file: undefined,
        image: undefined
    },
    {
        id: 61,
        quetion: "Is the branding on the <strong>FSU</strong> same as the one displayed in the below picture?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'fsu.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 62,
        quetion: "Is the SKU <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the FSU?",
        answer: undefined,
        productImage: "pr3.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 63,
        quetion: "How many facings of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr3.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 64,
        quetion: "Is the display of <strong>Skin Firming Nourishing Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr3.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 65,
        quetion: "Is the SKU <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong>, as shown in the image below, available on the FSU?",
        answer: undefined,
        productImage: "pr1.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 66,
        quetion: "How many facings of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr1.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 67,
        quetion: "Is the display of <strong>Skin Firming Sheer Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr1.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 68,
        quetion: "Is the SKU <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong>, shown in the image below, available on the FSU?",
        answer: undefined,
        productImage: "pr2.jpg",
        time: 0,
        type: "single-question-yes-no",
    },
    {
        id: 69,
        quetion: "How many facings of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> are kept on the FSU shelves?",
        answer: undefined,
        time: 0,
        type: "meter-count",
        productImage: 'pr2.jpg',
        counts: 0,
        file: "",
        image: ""
    },
    {
        id: 70,
        quetion: "Is the display of <strong>Skin Firming Melanin Beauty and Hydration 400 ML Body Lotion</strong> on the FSU Shelves same as displayed in the FSU Image shown below?",
        answer: undefined,
        time: 0,
        type: "single-question-yes-no",
        productImage: 'pr2.jpg',
        counts: 0,
        file: "",
        image: ""
    }
]